# Generated by Django 2.2.6 on 2021-11-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20211109_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='value_one',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='value_three',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='value_two',
            field=models.TextField(default='', max_length=250),
        ),
    ]
