# Generated by Django 2.2.6 on 2022-04-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20220317_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='imageURL',
            field=models.URLField(blank=True, default='https://bin.snmmd.nl/m/78x73ij2tm1d_1200x600.jpg/blog_podcastboeken.jpg'),
        ),
    ]
